# Generated by Django 6.0.3 on 2026-04-05 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryManager',
        ),
        migrations.AlterModelManagers(
            name='category',
            managers=[
            ],
        ),
    ]
