# Generated by Django 6.0.3 on 2026-05-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_delete_categorymanager_alter_category_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/brands/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/categories/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/main/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='images',
            field=models.ImageField(upload_to='images/product/gallery'),
        ),
    ]
